Day 1 Hands on quick exercise: Part 2: 10 mins
 
Creating a dummy data of 34 data items or more
explore the data: type. shape, mathematical operations
Convert your dummy data into an array.
type. shape, mathematical operations

In [8]:
import os
print(os.getcwd())

C:\Users\DELL\OneDrive\Desktop\New folder


In [11]:
data = [97, 2, 43, 56, 39, 21, 54, 73, 52, 48, 33, 42, 36, 67, 50, 55, 81, 12, 12, 85, 2, 33, 50, 94,
 51, 94, 7, 11, 85, 44, 59, 84, 73, 61, 86]

In [12]:
print(data)

[97, 2, 43, 56, 39, 21, 54, 73, 52, 48, 33, 42, 36, 67, 50, 55, 81, 12, 12, 85, 2, 33, 50, 94, 51, 94, 7, 11, 85, 44, 59, 84, 73, 61, 86]


In [13]:
type(data)

list

In [14]:
shape.data # list data not allow to shape

NameError: name 'shape' is not defined

In [16]:
# Convert your dummy data into an array.
import numpy as np

dummy_data = np.array(data)
print(dummy_data)

[97  2 43 56 39 21 54 73 52 48 33 42 36 67 50 55 81 12 12 85  2 33 50 94
 51 94  7 11 85 44 59 84 73 61 86]


In [17]:
type(dummy_data)

numpy.ndarray

In [18]:
np.shape(dummy_data)

(35,)

In [19]:
np.mean(dummy_data)

51.2

In [20]:
np.median(dummy_data)

51.0

Day 1 Hands on exercise : Part 2:
 
Lab Practice Problems for Python Libraries in Data Analysis
Objective: Introduce new learners to Python's NumPy and pandas libraries for basic data manipulation and analysis using DataFrame
Problem 1: Getting Started with NumPy
Create a 1D NumPy array with the numbers 1 to 10.
Reshape the array into a 2x5 matrix.
Extract the first row and the second column of the matrix.
Compute the mean, sum, and standard deviation of all elements in the matrix.
Problem 2: Understanding pandas DataFrame
Create a pandas DataFrame with the following data:
Name	Age	Gender	City	Marks
Alice	20	F	New York	85
Bob	22	M	Boston	90
Carol	19	F	Chicago	78
Dave	21	M	Seattle	88
 
 
These exercises will help learners build a strong foundation in using NumPy and pandas for data manipulation and analysis!

In [40]:
# problem 1:
import numpy as np

# Create and reshape the array
array_1d = np.arange(1, 11)
matrix_2x5 = array_1d.reshape(2, 5)

# Extract the first row
first_row = matrix_2x5[0, :]  

# Extract the second column
second_column = matrix_2x5[:, 1]  

# Compute statistics
mean_value = np.mean(matrix_2x5)  
sum_value = np.sum(matrix_2x5)    
std_deviation = np.std(matrix_2x5) 

# Output
print("Matrix:")
print(matrix_2x5)

print("\nFirst Row:")
print(first_row)

print("\nSecond Column:")
print(second_column)

print("\nStatistics:")
print(f"Mean: {mean_value}")
print(f"Sum: {sum_value}")
print(f"Standard Deviation: {std_deviation}")

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

First Row:
[1 2 3 4 5]

Second Column:
[2 7]

Statistics:
Mean: 5.5
Sum: 55
Standard Deviation: 2.8722813232690143


In [42]:
# Problem 2:
import pandas as pd

# Data dictionary
data = {
    "Name": ["Alice", "Bob", "Carol", "Dave"],
    "Age": [20, 22, 19, 21],
    "Gender": ["F", "M", "F", "M"],
    "City": ["New York", "Boston", "Chicago", "Seattle"],
    "Marks": [85, 90, 78, 88]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
df


Name  Age Gender      City  Marks
0  Alice   20      F  New York     85
1    Bob   22      M    Boston     90
2  Carol   19      F   Chicago     78
3   Dave   21      M   Seattle     88